TASKS = {
    "easy": [
        {
            "id": 1,
            "subject": "Win iPhone!!!",
            "body": "Click now to claim",
            "sender": "promo@spam.com",
            "priority": "low",
            "label": "mark_spam",
        },
        {
            "id": 2,
            "subject": "Refund request",
            "body": "I want my money back",
            "sender": "user@gmail.com",
            "priority": "medium",
            "label": "reply",
        },
    ],
    "medium": [
        {
            "id": 1,
            "subject": "URGENT refund",
            "body": "Refund immediately",
            "sender": "user2@gmail.com",
            "priority": "high",
            "label": "escalate",
        },
        {
            "id": 2,
            "subject": "Lottery Winner",
            "body": "Claim prize",
            "sender": "lottery@fake.com",
            "priority": "low",
            "label": "mark_spam",
        },
        {
            "id": 3,
            "subject": "Login issue",
            "body": "Can't login",
            "sender": "user3@gmail.com",
            "priority": "medium",
            "label": "reply",
        },
    ],
    "hard": [
        {
            "id": 1,
            "subject": "Refund maybe?",
            "body": "Not sure but I think I was charged twice",
            "sender": "user4@gmail.com",
            "priority": "medium",
            "label": "reply",
        },
        {
            "id": 2,
            "subject": "Free crypto!!!",
            "body": "Click fast",
            "sender": "crypto@scam.com",
            "priority": "low",
            "label": "mark_spam",
        },
        {
            "id": 3,
            "subject": "LEGAL NOTICE",
            "body": "Immediate response required",
            "sender": "legal@company.com",
            "priority": "high",
            "label": "escalate",
        },
        {
            "id": 4,
            "subject": "Help needed",
            "body": "App not working",
            "sender": "user5@gmail.com",
            "priority": "medium",
            "label": "reply",
        },
    ],
}